name: Insecure CI
on:
    push:
    pull_request:
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Print environment variables
      run: env
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    - name: Run build
      run: echo "Build completed"
